version: '3'
services:  
  homeassistant:    
    container_name: mydigitalschool_omega
    image: "ghcr.io/home-assistant/home-assistant:stable"    
    volumes:      
      - /home/debian/mydigitalschool/config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:      
      - 8129:8129
    restart: unless-stopped
    privileged: true