version: '3'
services:  
  homeassistant:    
    container_name: $society_omega
    image: "ghcr.io/home-assistant/home-assistant:stable"    
    volumes:      
      - /home/debian/$society/config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:      
      - $port:$port
    restart: unless-stopped
    privileged: true